### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by OmgImAlexis** [jakobwesthoff/prettytable.sh#2]
@jakobwesthoff any chance you could add a license to this?

**Comment by jakobwesthoff** [comment]
Sure thing. I hope MIT fits you needs?

**Comment by jakobwesthoff** [comment]
I just realized I already had the BSD-2-clause license mentioned within the shell file itself. I adapted the LICENSE file to this as well. Eventhough the licenses are quire similar I wanted to avoid confusion
