### ISSUE TITLE
Couldn't get this working unless I removed the bottom section

### ISSUE THREAD

**Issue by marijuanatech** [jakobwesthoff/prettytable.sh#3]
I couldn't get this to work when trying to "source" it into another script unless I removed the bottom four lines.

```
case $- in
  *i*) ;; # assume being sourced, do nothing
  *) prettytable $* ;; # assume being executed as an executable
esac
```

Am I doing something wrong?  The script just hangs.

**Comment by mikeroq** [comment]
I was able to get it working in source and executed by changing that block to:
```bash
[ "$0" = "$BASH_SOURCE" ] && prettytable $* || :
```

**Comment by marijuanatech** [comment]
Thank you!

**Comment by jakobwesthoff** [comment]
Thanks for bringing up the issue. I have adapted the script to accommodate your fix.
