### ISSUE TITLE
Feature request add support for basher installation of script

### ISSUE THREAD

**Issue by disaac** [jakobwesthoff/prettytable.sh#5]
Add support for [basher](https://github.com/basherpm/basher) install of script.

**Comment by jakobwesthoff** [comment]
A pull request for making the repo basher compatible would be highly welcome.

**Comment by disaac** [comment]
> A pull request for making the repo basher compatible would be highly welcome.

Added. Yeah created issue first so I could reference it in PR. Wow that was fast reply thanks so much for the helpful script 👍

**Comment by jakobwesthoff** [comment]
Perfect 👍. Thanks the PR is merged.
